=== jrossign/CTRLProxy/src/main/resources/schema/ctrl/detail/Details.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "Type": {
      "type": "string"
    },
    "Document": {
      "type": "string"
    },
    "Ligne": {
      "type": "string"
    },
    "Projet": {
      "type": "string"
    },
    "Activite": {
      "type": "string"
    },
    "Equipement": {
      "type": "string"
    },
    "Extra": {
      "type": "string"
    },
    "CategorieCout": {
      "type": "string"
    },
    "TravauxCours": {
      "type": "string"
    },
    "Division": {
      "type": "string"
    },
    "Item": {
      "type": "string"
    },
    "Version": {
      "type": "string"
    },
    "Entrepot": {
      "type": "string"
    },
    "Transaction1Serie": {
      "type": "string"
    },
    "Transaction1Quantite": {
      "type": "string"
    },
    "Transaction1Unite": {
      "type": "string"
    },
    "Transaction2Quantite": {
      "type": "string"
    },
    "Transaction2Unite": {
      "type": "string"
    },
    "PrixUnitaireTransaction1": {
      "type": "string"
    },
    "EscompteTransaction1": {
      "type": "string"
    },
    "SousTotalApresEscompteTransaction1": {
      "type": "string"
    },
    "Taxe1Transaction1": {
      "type": "string"
    },
    "Taxe2Transaction1": {
      "type": "string"
    },
    "GrandTotalTransaction1": {
      "type": "string"
    },
    "PrixUnitaireTransaction2": {
      "type": "string"
    },
    "EscompteTransaction2": {
      "type": "string"
    },
    "SousTotalApresEscompteTransaction2": {
      "type": "string"
    },
    "Taxe1Transaction2": {
      "type": "string"
    },
    "Taxe2Transaction2": {
      "type": "string"
    },
    "GrandTotalTransaction2": {
      "type": "string"
    },
    "Statut": {
      "type": "string"
    },
    "QuantiteSuspend": {
      "type": "string"
    },
    "CodeTaxe1": {
      "type": "string"
    },
    "CodeTaxe2": {
      "type": "string"
    },
    "DescriptionLigne": {
      "type": "string"
    },
    "MontantRetenuetaxesApresRetenueTransaction2": {
      "type": "string"
    },
    "MontantRetenuetaxesApresRetenueTransaction1": {
      "type": "string"
    },
    "NoPiece": {
      "type": "string"
    },
    "QuantiteDejaTraitee": {
      "type": "string"
    },
    "QuantiteAnnulee": {
      "type": "string"
    },
    "MontantDejaTraite": {
      "type": "string"
    },
    "MontantSuspens": {
      "type": "string"
    },
    "MontantAnnule": {
      "type": "string"
    },
    "DateLivraison": {
      "type": "string"
    },
    "PourcentageRetenuetaxesApresRetenueTransaction1": {
      "type": "string"
    },
    "PourcentageRetenuetaxesAvantRetenueTransaction1": {
      "type": "string"
    },
    "MontantRetenuetaxesAvantRetenueTransaction1": {
      "type": "string"
    },
    "PourcentageRetenuetaxesApresRetenueTransaction2": {
      "type": "string"
    },
    "PourcentageRetenuetaxesAvantRetenueTransaction2": {
      "type": "string"
    },
    "MontantRetenuetaxesAvantRetenueTransaction2": {
      "type": "string"
    },
    "PourcentageEscompteTransaction1": {
      "type": "string"
    },
    "PourcentageEscompteTransaction2": {
      "type": "string"
    },
    "SousTotalAvantAjustementTransaction1": {
      "type": "string"
    },
    "SousTotalAvantAjustementTransaction2": {
      "type": "string"
    },
    "Reference1": {
      "type": "string"
    },
    "Reference2": {
      "type": "string"
    },
    "Reference3": {
      "type": "string"
    },
    "CodeTaxe1Transaction2": {
      "type": "string"
    },
    "CodeTaxe2Transaction2": {
      "type": "string"
    },
    "Transaction1QuantiteMaitre": {
      "type": "string"
    },
    "Transaction1MontantMaitre": {
      "type": "string"
    },
    "QuantiteDejaTraiteeMaitre": {
      "type": "string"
    },
    "MontantDejaTraiteMaitre": {
      "type": "string"
    },
    "QuantiteSuspendMaitre": {
      "type": "string"
    },
    "MontantSuspendMaitre": {
      "type": "string"
    },
    "QuantiteAnnuleeMaitre": {
      "type": "string"
    },
    "MontantAnnuleMaitre": {
      "type": "string"
    },
    "Compagnie": {
      "type": "string"
    },
    "Ordre": {
      "type": "string"
    },
    "LigneGeneree": {
      "type": "string"
    },
    "DossierPatient": {
      "type": "string"
    },
    "Commentaire": {
      "type": "string"
    },
    "Transaction2Serie": {
      "type": "string"
    },
    "SerieTraites": {
      "type": "string"
    },
    "MontantArrondiAjustement": {
      "type": "string"
    },
    "MontantArrondiRetenuetaxesApresRetenue": {
      "type": "string"
    },
    "MontantArrondiRetenuetaxesAvantRetenue": {
      "type": "string"
    },
    "Modalite": {
      "type": "string"
    },
    "NumeroDepot": {
      "type": "string"
    },
    "LigneDocumentMaitre": {
      "type": "string"
    },
    "NumeroFactureAvance": {
      "type": "string"
    },
    "FrequenceInitialeDescription": {
      "type": "string"
    },
    "FrequenceInitialeQuantite": {
      "type": "string"
    },
    "FrequenceInitialeUnite": {
      "type": "string"
    },
    "FrequenceInitialePrixUnitaire": {
      "type": "string"
    },
    "FrequenceInitialePeriode": {
      "type": "string"
    },
    "FrequenceInitialeFrequence": {
      "type": "string"
    },
    "FrequencePeriodiqueDescription": {
      "type": "string"
    },
    "FrequencePeriodiqueQuantite": {
      "type": "string"
    },
    "FrequencePeriodiqueUnite": {
      "type": "string"
    },
    "FrequencePeriodiquePrixUnitaire": {
      "type": "string"
    },
    "FrequencePeriodiquePeriode": {
      "type": "string"
    },
    "FrequencePeriodiqueFrequence": {
      "type": "string"
    },
    "FrequencePeriodiqueNombre": {
      "type": "string"
    },
    "FrequenceFinaleDescription": {
      "type": "string"
    },
    "FrequenceFinaleQuantite": {
      "type": "string"
    },
    "FrequenceFinaleUnite": {
      "type": "string"
    },
    "FrequenceFinalePrixUnitaire": {
      "type": "string"
    },
    "FrequenceMaximumQuantite": {
      "type": "string"
    },
    "FrequenceMaximumUnite": {
      "type": "string"
    },
    "FrequenceMaximumMontant": {
      "type": "string"
    },
    "FrequenceInititaleDateDebut": {
      "type": "string"
    },
    "FrequencePeriodiqueDateDebut": {
      "type": "string"
    },
    "DateDebutFrequence": {
      "type": "string"
    },
    "DateFinFrequence": {
      "type": "string"
    },
    "GestionQuantites": {
      "type": "string"
    },
    "MontantRetenueretenueApresTaxesTransaction1": {
      "type": "string"
    },
    "MontantRetenueretenueApresTaxesTransaction2": {
      "type": "string"
    },
    "PourcentageRetenueRetenueApresTaxesTransaction1": {
      "type": "string"
    },
    "PourcentageRetenueRetenueApresTaxesTransaction2": {
      "type": "string"
    },
    "MontantArrondiRetenueretenueApresTaxes": {
      "type": "string"
    },
    "IdentifiantUnique": {
      "type": "string"
    },
    "FrequenceInitialeDefautDocumentProduitDescription": {
      "type": "string"
    },
    "FrequenceInitialeDefautDocumentProduitQuantite": {
      "type": "string"
    },
    "FrequenceInitialeDefautDocumentProduitUnite": {
      "type": "string"
    },
    "FrequenceInitialeDefautDocumentProduitPrixUnitaire": {
      "type": "string"
    },
    "FrequenceInitialeDefautDocumentProduitPeriode": {
      "type": "string"
    },
    "FrequenceInitialeDefautDocumentProduitFrequence": {
      "type": "string"
    },
    "FrequencePeriodiqueDefautDocumentProduitDescription": {
      "type": "string"
    },
    "FrequencePeriodiqueDefautDocumentProduitQuantite": {
      "type": "string"
    },
    "FrequencePeriodiqueDefautDocumentProduitUnite": {
      "type": "string"
    },
    "FrequencePeriodiqueDefautDocumentProduitPrixUnitair": {
      "type": "string"
    },
    "FrequencePeriodiqueDefautDocumentProduitPeriode": {
      "type": "string"
    },
    "FrequencePeriodiqueDefautDocumentProduitFrequence": {
      "type": "string"
    },
    "FrequencePeriodiqueDefautDocumentProduitNombre": {
      "type": "string"
    },
    "FrequenceFinaleDefautDocumentProduitDescription": {
      "type": "string"
    },
    "FrequenceFinaleDefautDocumentProduitQuantite": {
      "type": "string"
    },
    "FrequenceFinaleDefautDocumentProduitUnite": {
      "type": "string"
    },
    "FrequenceFinaleDefautDocumentProduitPrixUnitaire": {
      "type": "string"
    },
    "FrequenceModalite": {
      "type": "string"
    },
    "CTITaxe1Transaction1": {
      "type": "string"
    },
    "CTITaxe2Transaction1": {
      "type": "string"
    },
    "CTITaxe1Transaction2": {
      "type": "string"
    },
    "CTITaxe2Transaction2": {
      "type": "string"
    },
    "LigneItemMaitreListeMateriel": {
      "type": "string"
    },
    "CodeCatalogue": {
      "type": "string"
    },
    "CodeFabricant": {
      "type": "string"
    },
    "PieceFabricant": {
      "type": "string"
    },
    "TransactionSousTraitance": {
      "type": "string"
    },
    "VersionRecord": {
      "type": "string"
    },
    "TimestampDerniereSauvegarde": {
      "type": "string"
    },
    "TypeDocumentMaitre": {
      "type": "string"
    },
    "DocumentMaitre": {
      "type": "string"
    },
    "Majoration1Transaction1": {
      "type": "string"
    },
    "Majoration2Transaction1": {
      "type": "string"
    },
    "Majoration1Transaction2": {
      "type": "string"
    },
    "Majoration2Transaction2": {
      "type": "string"
    },
    "PourcMajoration1Transaction1": {
      "type": "string"
    },
    "PourcMajoration2Transaction1": {
      "type": "string"
    },
    "PourcMajoration1Transaction2": {
      "type": "string"
    },
    "PourcMajoration2Transaction2": {
      "type": "string"
    },
    "NiveauApplicationMajoration1": {
      "type": "string"
    },
    "NiveauApplicationMajoration2": {
      "type": "string"
    },
    "CategorieVendant": {
      "type": "string"
    },
    "VentilationMaitre": {
      "type": "string"
    },
    "PourcentageAvancement": {
      "type": "string"
    },
    "PourcentageAvancementLivraison": {
      "type": "string"
    },
    "TypeVentilation": {
      "type": "string"
    },
    "ActionType": {
      "type": "string"
    }
  },
  "required": [
    "Type",
    "Document"
  ]
}

=== jrossign/CTRLProxy/src/test/resources/messages/ctrl/details-2.json
{
  "Type" : "BSP",
  "Document" : "BSP00281",
  "Projet" : "0936",
  "Activite" : "20830",
  "Transaction1Quantite" : "76",
  "PrixUnitaireTransaction1" : "79",
  "Statut" : "SUS",
  "DescriptionLigne" : "S-22284 FB 1/2\" x 20' a faire chanfrein de 1/2\" avec meplat de 1/8\" sur un c\u00F4t\u00E9 seulement",
  "Compagnie" : "001",
  "Ordre" : "1"
}

=== jrossign/CTRLProxy/src/test/resources/messages/ctrl/details-1.json
[
  {
    "Type": "BSP",
    "Document": "BSP1",
    "Ligne": "1",
    "Projet": "0867",
    "Activite": "10010",
    "Extra": "",
    "Equipement": "",
    "CategorieCout": "2",
    "TravauxCours": "N",
    "Division": "001",
    "Item": "",
    "Version": "",
    "Entrepot": "",
    "Transaction1Serie": "",
    "Transaction1Quantite": "2",
    "Transaction1Unite": "PND",
    "Transaction2Quantite": "",
    "Transaction2Unite": "",
    "PrixUnitaireTransaction1": "0.85",
    "EscompteTransaction1": "",
    "SousTotalApresEscompteTransaction1": "",
    "Taxe1Transaction1": "",
    "Taxe2Transaction1": "",
    "GrandTotalTransaction1": "2107.184",
    "PrixUnitaireTransaction2": "",
    "EscompteTransaction2": "",
    "SousTotalApresEscompteTransaction2": "",
    "Taxe1Transaction2": "0",
    "Taxe2Transaction2": "0",
    "GrandTotalTransaction2": "0",
    "Statut": "ACT",
    "QuantiteSuspend": "2560",
    "CodeTaxe1": "TF",
    "CodeTaxe2": "TP",
    "DescriptionLigne": "L2X2X3/16 44W X6096 mm",
    "MontantRetenuetaxesApresRetenueTransaction2": "0",
    "MontantRetenuetaxesApresRetenueTransaction1": "0",
    "NoPiece": "",
    "QuantiteDejaTraitee": "0",
    "QuantiteAnnulee": "0",
    "MontantDejaTraite": "0",
    "MontantSuspens": "",
    "MontantAnnule": "0",
    "DateLivraison": "",
    "PourcentageRetenuetaxesApresRetenueTransaction1": "0",
    "PourcentageRetenuetaxesAvantRetenueTransaction1": "0",
    "MontantRetenuetaxesAvantRetenueTransaction1": "0",
    "PourcentageRetenuetaxesApresRetenueTransaction2": "0",
    "PourcentageRetenuetaxesAvantRetenueTransaction2": "0",
    "MontantRetenuetaxesAvantRetenueTransaction2": "0",
    "PourcentageEscompteTransaction1": "0",
    "PourcentageEscompteTransaction2": "0",
    "SousTotalAvantAjustementTransaction1": "",
    "SousTotalAvantAjustementTransaction2": "",
    "Reference1": "",
    "Reference2": "",
    "Reference3": "",
    "CodeTaxe1Transaction2": "TF",
    "CodeTaxe2Transaction2": "TP",
    "Transaction1QuantiteMaitre": "0",
    "Transaction1MontantMaitre": "0",
    "QuantiteDejaTraiteeMaitre": "0",
    "MontantDejaTraiteMaitre": "0",
    "QuantiteSuspendMaitre": "0",
    "MontantSuspendMaitre": "0",
    "QuantiteAnnuleeMaitre": "0",
    "MontantAnnuleMaitre": "0",
    "Compagnie": "001",
    "Ordre": "1",
    "LigneGeneree": "N",
    "DossierPatient": "",
    "Commentaire": "",
    "Transaction2Serie": "",
    "SerieTraites": "",
    "MontantArrondiAjustement": "0",
    "MontantArrondiRetenuetaxesApresRetenue": "0",
    "MontantArrondiRetenuetaxesAvantRetenue": "0",
    "Modalite": "",
    "NumeroDepot": "",
    "LigneDocumentMaitre": "0",
    "NumeroFactureAvance": "",
    "FrequenceInitialeDescription": "",
    "FrequenceInitialeQuantite": "0",
    "FrequenceInitialeUnite": "",
    "FrequenceInitialePrixUnitaire": "0",
    "FrequenceInitialePeriode": "0",
    "FrequenceInitialeFrequence": "H",
    "FrequencePeriodiqueDescription": "",
    "FrequencePeriodiqueQuantite": "0",
    "FrequencePeriodiqueUnite": "",
    "FrequencePeriodiquePrixUnitaire": "0",
    "FrequencePeriodiquePeriode": "0",
    "FrequencePeriodiqueFrequence": "H",
    "FrequencePeriodiqueNombre": "0",
    "FrequenceFinaleDescription": "",
    "FrequenceFinaleQuantite": "0",
    "FrequenceFinaleUnite": "UNI",
    "FrequenceFinalePrixUnitaire": "0",
    "FrequenceMaximumQuantite": "0",
    "FrequenceMaximumUnite": "UNI",
    "FrequenceMaximumMontant": "0",
    "FrequenceInititaleDateDebut": "",
    "FrequencePeriodiqueDateDebut": "",
    "DateDebutFrequence": "",
    "DateFinFrequence": "",
    "GestionQuantites": "M",
    "MontantRetenueretenueApresTaxesTransaction1": "0",
    "MontantRetenueretenueApresTaxesTransaction2": "0",
    "PourcentageRetenueRetenueApresTaxesTransaction1": "0",
    "PourcentageRetenueRetenueApresTaxesTransaction2": "0",
    "MontantArrondiRetenueretenueApresTaxes": "0",
    "IdentifiantUnique": "",
    "FrequenceInitialeDefautDocumentProduitDescription": "",
    "FrequenceInitialeDefautDocumentProduitQuantite": "0",
    "FrequenceInitialeDefautDocumentProduitUnite": "UNI",
    "FrequenceInitialeDefautDocumentProduitPrixUnitaire": "0",
    "FrequenceInitialeDefautDocumentProduitPeriode": "0",
    "FrequenceInitialeDefautDocumentProduitFrequence": "H",
    "FrequencePeriodiqueDefautDocumentProduitDescription": "",
    "FrequencePeriodiqueDefautDocumentProduitQuantite": "0",
    "FrequencePeriodiqueDefautDocumentProduitUnite": "UNI",
    "FrequencePeriodiqueDefautDocumentProduitPrixUnitair": "0",
    "FrequencePeriodiqueDefautDocumentProduitPeriode": "0",
    "FrequencePeriodiqueDefautDocumentProduitFrequence": "H",
    "FrequencePeriodiqueDefautDocumentProduitNombre": "0",
    "FrequenceFinaleDefautDocumentProduitDescription": "",
    "FrequenceFinaleDefautDocumentProduitQuantite": "0",
    "FrequenceFinaleDefautDocumentProduitUnite": "UNI",
    "FrequenceFinaleDefautDocumentProduitPrixUnitaire": "0",
    "FrequenceModalite": "",
    "CTITaxe1Transaction1": "",
    "CTITaxe2Transaction1": "",
    "CTITaxe1Transaction2": "0",
    "CTITaxe2Transaction2": "0",
    "LigneItemMaitreListeMateriel": "0",
    "CodeCatalogue": "",
    "CodeFabricant": "",
    "PieceFabricant": "",
    "TransactionSousTraitance": "N",
    "VersionRecord": "",
    "TimestampDerniereSauvegarde": "2022-06-07 hh:mm:ss",
    "TypeDocumentMaitre": "",
    "DocumentMaitre": "",
    "Majoration1Transaction1": "0",
    "Majoration2Transaction1": "0",
    "Majoration1Transaction2": "0",
    "Majoration2Transaction2": "0",
    "PourcMajoration1Transaction1": "0",
    "PourcMajoration2Transaction1": "0",
    "PourcMajoration1Transaction2": "0",
    "PourcMajoration2Transaction2": "0",
    "NiveauApplicationMajoration1": "1",
    "NiveauApplicationMajoration2": "1",
    "CategorieVendant": "2",
    "VentilationMaitre": "0",
    "PourcentageAvancement": "0",
    "PourcentageAvancementLivraison": "0",
    "TypeVentilation": "A"
  }
]
