=== jrossign/CTRLProxy/src/main/resources/schema/ctrl/header/Header.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "Type": {
      "type": "string"
    },
    "Document": {
      "type": "string"
    },
    "Description": {
      "type": "string"
    },
    "DocumentMaitre": {
      "type": "string"
    },
    "TypeDocumentMaitre": {
      "type": "string"
    },
    "Intervenant": {
      "type": "string"
    },
    "NomIntervenant": {
      "type": "string"
    },
    "Statut": {
      "type": "string"
    },
    "DateDocument": {
      "type": "string"
    },
    "DateCreation": {
      "type": "string"
    },
    "UsagerResponsable": {
      "type": "string"
    },
    "UsagerInscripteur": {
      "type": "string"
    },
    "DateModification": {
      "type": "string"
    },
    "UsagerModificateur": {
      "type": "string"
    },
    "Reference1": {
      "type": "string"
    },
    "Reference2": {
      "type": "string"
    },
    "Contact": {
      "type": "string"
    },
    "Territoire": {
      "type": "string"
    },
    "LivraisonTransporteur": {
      "type": "string"
    },
    "LivraisonDateFin": {
      "type": "string"
    },
    "CommentaireGeneral": {
      "type": "string"
    },
    "RetenueCommande": {
      "type": "string",
      "default": "N"
    },
    "TypeRetenue": {
      "type": "string",
      "default": "N"
    },
    "Conditions": {
      "type": "string"
    },
    "AdresseLivraison": {
      "type": "string"
    },
    "VilleLivraison": {
      "type": "string"
    },
    "ProvinceLivraison": {
      "type": "string"
    },
    "CodePostal": {
      "type": "string"
    },
    "AdresseFacturation": {
      "type": "string"
    },
    "VilleFacturation": {
      "type": "string"
    },
    "ProvinceFacturation": {
      "type": "string"
    },
    "CodePostalFacturation": {
      "type": "string"
    },
    "CompagnieSource": {
      "type": "string"
    },
    "CompagnieDestination": {
      "type": "string"
    },
    "FrequenceFacturation": {
      "type": "string"
    },
    "DateDebutFrequence": {
      "type": "string"
    },
    "Devise": {
      "type": "string"
    },
    "SousTotal": {
      "type": "string"
    },
    "MontantAjustement": {
      "type": "string"
    },
    "MontantTaxe1": {
      "type": "string"
    },
    "MontantTaxe2": {
      "type": "string"
    },
    "LivraisonDateDebut": {
      "type": "string"
    },
    "AdresseLivraisonLigne2": {
      "type": "string"
    },
    "PaysLivraison": {
      "type": "string"
    },
    "AdresseFacturationLigne2": {
      "type": "string"
    },
    "PaysFacturation": {
      "type": "string"
    },
    "DateDerniereImpression": {
      "type": "string"
    },
    "LangueIntervenant": {
      "type": "string"
    },
    "Facture": {
      "type": "string"
    },
    "Prefixe": {
      "type": "string"
    },
    "DateFacture": {
      "type": "string"
    },
    "MontantRetenue": {
      "type": "string"
    },
    "FrequencePeriode": {
      "type": "string"
    },
    "DateFinFrequence": {
      "type": "string"
    },
    "DatePremiereFrequence": {
      "type": "string"
    },
    "SousTotalTransaction2": {
      "type": "string"
    },
    "MontantAjustementTransaction2": {
      "type": "string"
    },
    "MontantTaxe1Transaction2": {
      "type": "string"
    },
    "MontantTaxe2Transaction2": {
      "type": "string"
    },
    "MontantRetenueTransaction2": {
      "type": "string"
    },
    "MontantDejaTraiteMaitre": {
      "type": "string"
    },
    "ImpressionSommaire": {
      "type": "string"
    },
    "Reference3": {
      "type": "string"
    },
    "Reference4": {
      "type": "string"
    },
    "Reference5": {
      "type": "string"
    },
    "FrequenceDescription": {
      "type": "string"
    },
    "Description2": {
      "type": "string"
    },
    "DossierFacturation": {
      "type": "string"
    },
    "DescriptionFacturation": {
      "type": "string"
    },
    "Description2Facturation": {
      "type": "string"
    },
    "ContactFacturation": {
      "type": "string"
    },
    "DossierLivraison": {
      "type": "string"
    },
    "DescriptionLivraison": {
      "type": "string"
    },
    "Description2Livraison": {
      "type": "string"
    },
    "ContactLivraison": {
      "type": "string"
    },
    "SousTotalDejaTraiteMaitre": {
      "type": "string"
    },
    "MontantSuspens": {
      "type": "string"
    },
    "TypeDocumentEngagement": {
      "type": "string"
    },
    "DocumentEngagement": {
      "type": "string"
    },
    "IdentifiantUnique": {
      "type": "string"
    },
    "LivraisonDateDebutReelle": {
      "type": "string"
    },
    "LivraisonDateReelle": {
      "type": "string"
    },
    "FrequenceImpressionDescription": {
      "type": "string"
    },
    "FrequenceImpressionPeriode": {
      "type": "string"
    },
    "FrequenceImpression": {
      "type": "string"
    },
    "DateDebutDerniereImpression": {
      "type": "string"
    },
    "DateFinDerniereImpression": {
      "type": "string"
    },
    "DatePremiereImpression": {
      "type": "string"
    },
    "DateDenonciation": {
      "type": "string"
    },
    "MontantDenonce": {
      "type": "string"
    },
    "QuittanceRecue": {
      "type": "string"
    },
    "QuittanceRecevoir": {
      "type": "string"
    },
    "MiseJour": {
      "type": "string"
    },
    "TelephoneContact": {
      "type": "string"
    },
    "TelephoneFacturation": {
      "type": "string"
    },
    "TelephoneLivraison": {
      "type": "string"
    },
    "TypeIntervenant": {
      "type": "string"
    },
    "TypeIntervenantFacturation": {
      "type": "string"
    },
    "TypeIntervenantLivraison": {
      "type": "string"
    },
    "CompagnieIntervenant": {
      "type": "string"
    },
    "CompagnieIntervenantFacturation": {
      "type": "string"
    },
    "CompagnieIntervenantLivraison": {
      "type": "string"
    },
    "CompagnieLiee": {
      "type": "string"
    },
    "Consolidation": {
      "type": "string"
    },
    "Reference6": {
      "type": "string"
    },
    "Reference7": {
      "type": "string"
    },
    "Reference8": {
      "type": "string"
    },
    "Reference9": {
      "type": "string"
    },
    "Reference10": {
      "type": "string"
    },
    "Reference11": {
      "type": "string"
    },
    "Reference12": {
      "type": "string"
    },
    "Reference13": {
      "type": "string"
    },
    "Reference14": {
      "type": "string"
    },
    "Reference15": {
      "type": "string"
    },
    "Succursale": {
      "type": "string"
    },
    "VersionRecord": {
      "type": "string"
    },
    "TimestampDerniereSauvegarde": {
      "type": "string"
    },
    "Projet": {
      "type": "string"
    },
    "TypeGeneration": {
      "type": "string"
    },
    "RevisionDocument": {
      "type": "string"
    },
    "Num√©roFactureATraiter": {
      "type": "string"
    },
    "DateFactureATraiter": {
      "type": "string"
    },
    "DateTransactionFactureATraiter": {
      "type": "string"
    },
    "DateDebutDocument": {
      "type": "string"
    },
    "DateFinDocument": {
      "type": "string"
    }
  },
  "required": [
    "Type",
    "Document"
  ]
}

=== jrossign/CTRLProxy/src/test/resources/messages/ctrl/header-1.json
[
  {
    "Type": "BSP",
    "Document": "BSP1",
    "Description": "Acier Picard",
    "DocumentMaitre": "",
    "TypeDocumentMaitre": "",
    "Intervenant": "F00190",
    "NomIntervenant": "Acier Picard",
    "Statut": "ACT",
    "DateDocument": "2022-06-07",
    "DateCreation": "2022-06-07",
    "UsagerResponsable": "MATPER",
    "UsagerInscripteur": "WEBSTP",
    "DateModification": "2022-06-07",
    "UsagerModificateur": "MATPER",
    "Reference1": "BSP1",
    "Reference2": "BSP1",
    "Contact": "",
    "Territoire": "CA-QC",
    "LivraisonTransporteur": "",
    "LivraisonDateFin": "",
    "CommentaireGeneral": "",
    "RetenueCommande": "N",
    "TypeRetenue": "N",
    "Conditions": "",
    "AdresseLivraison": "",
    "VilleLivraison": "",
    "ProvinceLivraison": "",
    "CodePostal": "",
    "AdresseFacturation": "",
    "VilleFacturation": "",
    "ProvinceFacturation": "",
    "CodePostalFacturation": "",
    "CompagnieSource": "001",
    "CompagnieDestination": "001",
    "FrequenceFacturation": "N",
    "DateDebutFrequence": "",
    "Devise": "CAD",
    "SousTotal": "0",
    "MontantAjustement": "0",
    "MontantTaxe1": "0",
    "MontantTaxe2": "0",
    "LivraisonDateDebut": "",
    "AdresseLivraisonLigne2": "",
    "PaysLivraison": "",
    "AdresseFacturationLigne2": "",
    "PaysFacturation": "",
    "DateDerniereImpression": "",
    "LangueIntervenant": "FRA",
    "Facture": "",
    "Prefixe": "BSP",
    "DateFacture": "",
    "MontantRetenue": "0",
    "FrequencePeriode": "0",
    "DateFinFrequence": "",
    "DatePremiereFrequence": "",
    "SousTotalTransaction2": "0",
    "MontantAjustementTransaction2": "0",
    "MontantTaxe1Transaction2": "0",
    "MontantTaxe2Transaction2": "0",
    "MontantRetenueTransaction2": "0",
    "MontantDejaTraiteMaitre": "0",
    "ImpressionSommaire": "N",
    "Reference3": "",
    "Reference4": "",
    "Reference5": "",
    "FrequenceDescription": "",
    "Description2": "",
    "DossierFacturation": "F00166",
    "DescriptionFacturation": "Acier Altitube Inc.",
    "Description2Facturation": "",
    "ContactFacturation": "Nicolas Couvrette Roy",
    "DossierLivraison": "F00166",
    "DescriptionLivraison": "Acier Altitube Inc.",
    "Description2Livraison": "",
    "ContactLivraison": "Nicolas Couvrette Roy",
    "SousTotalDejaTraiteMaitre": "0",
    "MontantSuspens": "0",
    "TypeDocumentEngagement": "BSP",
    "DocumentEngagement": "BSP1",
    "IdentifiantUnique": "",
    "LivraisonDateDebutReelle": "",
    "LivraisonDateReelle": "",
    "FrequenceImpressionDescription": "",
    "FrequenceImpressionPeriode": "0",
    "FrequenceImpression": "N",
    "DateDebutDerniereImpression": "",
    "DateFinDerniereImpression": "",
    "DatePremiereImpression": "",
    "DateDenonciation": "",
    "MontantDenonce": "0",
    "QuittanceRecue": "0",
    "QuittanceRecevoir": "0",
    "MiseJour": "A",
    "TelephoneContact": "",
    "TelephoneFacturation":"",
    "TelephoneLivraison": "",
    "TypeIntervenant": "FOU",
    "TypeIntervenantFacturation": "FOU",
    "TypeIntervenantLivraison": "FOU",
    "CompagnieIntervenant": "",
    "CompagnieIntervenantFacturation": "",
    "CompagnieIntervenantLivraison": "",
    "CompagnieLiee": "001",
    "Consolidation": "I",
    "Reference6": "",
    "Reference7": "",
    "Reference8": "",
    "Reference9": "",
    "Reference10": "",
    "Reference11": "",
    "Reference12": "",
    "Reference13": "",
    "Reference14": "",
    "Reference15": "",
    "Succursale": "",
    "VersionRecord": "",
    "TimestampDerniereSauvegarde": "2022-06-07 hh:mm:ss",
    "Projet": "0867",
    "TypeGeneration": "",
    "RevisionDocument": "",
    "Num√©roFactureATraiter": "",
    "DateFactureATraiter": "",
    "DateTransactionFactureATraiter": "",
    "DateDebutDocument": "",
    "DateFinDocument": ""
  }
]
